## Written by https://github.com/anthonysecco
# Special thanks to Mike Goubeaux (Smarty Van)
# To be used with Undermount AC ESP Home Thermostat and Undermount AC System

# Connector Matrix:
# Output 1 - Blower Speed (White Wire)
# Output 2 - Blower Power On/Off (Brown Wire) 
# Output 3 - Low-Speed Compressor (Blue Wire)
# Output 4 - High-Speed Compressor (Green Wire)
# Output 5 - Unused
# Output 6 - Unused

# Substitutions
################################################################################
substitutions:
  device_name: undermount-ac
  friendly_name: "Undermount AC"

# Globals
################################################################################
globals:

  # Blower Ramp Globals
  - id: current_blower_speed
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: target_blower_speed
    type: float
    restore_value: no
    initial_value: '0.0'
  - id: ramp_blower
    type: bool
    restore_value: no
    initial_value: 'false'

# Board Configuration
################################################################################
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: anthonysecco.undermount-ac-esphome-thermostat
    version: "0.2.0-beta"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Connectivity
################################################################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.1.27
    gateway: 10.0.1.1
    subnet: 255.255.255.0
    dns1: 10.0.1.1
  output_power: 14db # 8.5db (lowest) and 20.5db (highest)
  ap: # Backup Access Point if Wi-Fi is unavailable
    ssid: "${friendly_name} Fallback AP"
    password: "12345678"

captive_portal:

# Core Services
################################################################################
logger:
  level: DEBUG # Change to DEBUG for more logs
api:

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://anthonysecco/undermount-ac-esphome-thermostat/blob/main/undermount-ac.yaml@dev-sweep-1
  import_full_config: true

# LEDs
################################################################################

# Sensors
################################################################################

sensor:
  - platform: template
    id: blower_speed_called
    name: "Output 1 (Blower Speed)"
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: ""
    entity_category: "diagnostic"
    icon: mdi:fan
    filters:
      - lambda: |-
          if(id(blower_fan).state) {
            return ((x * .01) * (id(blower_pwm).get_max_power() - id(blower_pwm).get_min_power()) + id(blower_pwm).get_min_power()) * 100;
          } else {
            return 0.0;
          }

  # Uncomment sensors below for Wi-Fi Diagnostics
  #- platform: wifi_signal
  #  name: "WiFi Signal dB"
  #  id: wifi_signal_db
  #  update_interval: 60s
  #  entity_category: "diagnostic"
  #  disabled_by_default: True
  #  icon: "mdi:wifi"

  #- platform: copy
  #  source_id: wifi_signal_db
  #  name: "WiFi Signal Percent"
  #  filters:
  #    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
  #  unit_of_measurement: "%"
  #  entity_category: "diagnostic"
  #  disabled_by_default: True
  #  icon: "mdi:wifi-strength-4"

binary_sensor:
  - platform: template
    name: "Output 2 (Blower Power)"
    id: blower_power_called
    device_class: "power"
    entity_category: "diagnostic"
    icon: "mdi:toggle-switch"
    lambda: |-
      return id(blower_power).is_enabled();
    disabled_by_default: true

  - platform: template
    name: "Ramp Blower"
    id: ramp_blower_diag
    device_class: "moving"
    entity_category: "diagnostic"
    icon: "mdi:rotate-right"
    lambda: |-
      return id(ramp_blower);
    disabled_by_default: true

#Outputs
################################################################################
output:
  - platform: ledc # Output 1
    pin: 7
    id: blower_pwm
    power_supply: blower_power
    frequency: 240 hz   # Frequency per Undermount AC
    min_power: 0.00     # Minimum duty cycle to start blower
    max_power: 1.00     # Max duty cycle per Undermount AC
    zero_means_zero: true

  - platform: template
    id: blower_pwm_filter
    type: float
    write_action:
      - lambda: |-
          // My testing indicates the blower has stair step transfer function.  These are reliable steps I've found.
          const float duty_cycles[25] = {
              0.01, 0.04, 0.08, 0.12,
              0.16, 0.20, 0.24, 0.28, 0.32,
              0.36, 0.40, 0.44, 0.48, 0.52,
              0.56, 0.60, 0.64, 0.68, 0.72,
              0.76, 0.80, 0.84, 0.88, 0.92, 0.96
          };

          // Calculate the speed index correctly
          int speed_index;
          if (state <= 0.0) {
              speed_index = 0;  // Map zero to the first element (0.01)
          } else {
              // Correctly calculate the speed index, using floor to avoid rounding issues
              speed_index = floor(state * 24);  // Multiplied by (25 - 1) to scale correctly
              speed_index = fmax(0, fmin(24, speed_index));  // Clamp to range 0-24
          }

          // Get the duty cycle from the pre-defined array
          float duty_cycle = duty_cycles[speed_index];

          id(blower_pwm).set_level(duty_cycle);
          ESP_LOGI("Blower PWM Filter", "State: %.2f, Speed Index: %d, Duty Cycle: %.2f", state, speed_index, duty_cycle);
          id(blower_speed_called).publish_state(duty_cycle * 100);

power_supply: 
  - id: blower_power # Output 2 
    pin: 
      number: 9
      inverted: true

fan:
  - platform: speed
    name: "Blower"
    output: blower_pwm_filter
    id: blower_fan
    disabled_by_default: true

number:      
  - platform: template
    name: "TEST: Blower Manual Speed Setting" # Use only when fan component blower is 'off'
    id: blower_speed
    min_value: 0.10
    max_value: 0.98
    step: 0.01  # Adjust step for fine control
    unit_of_measurement: "PWM"
    set_action:
      - output.set_level:
          id: blower_pwm
          level: !lambda 'return x;'

  - platform: template
    name: "TEST: Blower Ramp Speed Setting" # Use when fan component blower is 'on'
    id: blower_speed2
    min_value: 0.10
    max_value: 0.98
    step: 0.01  # Adjust step for fine control
    unit_of_measurement: "PWM"
    set_action:
    - lambda: |-
        id(target_blower_speed) = (x * 100);
        id(ramp_blower) = true;

# Climate
################################################################################

# Scripts
################################################################################

interval:
  - interval: 1000ms
    id: blower_ramp_control
    then:
      - lambda: |-
          ESP_LOGD("RAMP", "Ramp Blower: %d, Current Speed: %.2f, Target Speed: %.2f", 
                   id(ramp_blower), id(current_blower_speed), id(target_blower_speed));
          if (id(ramp_blower) && id(blower_fan).state) {
            // Sets ramp rate 0-100 over 98 seconds
            const float transition_time = 98.0;
            const float interval = 1.0; // 1s
            int steps = transition_time / interval;

            // Calculate the difference between current and target blower speed
            float diff = id(target_blower_speed) - id(current_blower_speed);

            // Fixed step size for consistent speed change
            const float step_size = 100.0 / steps;

            // Determine the direction of the step
            float step = (diff > 0) ? step_size : -step_size;

            // Calculate the next speed, including the step
            float next_speed = id(current_blower_speed) + step;

            // Clamp the speed within boundaries (min: 1, max: 100)
            next_speed = fmax(1, fmin(next_speed, 100));

            if (fabs(diff) < fabs(step)) {
                id(current_blower_speed) = (next_speed <= 1) ? 1 : next_speed;
                id(ramp_blower) = false;

                // Set the actual desired speed
                auto final_call = id(blower_fan).make_call();
                final_call.set_speed(id(current_blower_speed));
                final_call.perform();
            } else {
                // Update the current blower speed smoothly
                id(current_blower_speed) = next_speed;
                auto call = id(blower_fan).make_call();
                call.set_speed(id(current_blower_speed));
                call.perform();
            }
          }
